language: go
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lftp
install: go get -v github.com/spf13/hugo
script:
- hugo
deploy:
  provider: script
  script: ./deploy.sh
env:
  global:
  - secure: ja69orrzg9jm6+ytjmqNj/wVE5S1TyaJoL4TdoXCZi5VO2Mi8W7c8XWAY8CYRHPYLrwU/VFSrXzC0DOXSfLhPzLVpZrXHztWjXAeGu2dyQzvEqlSSpmU8GxpdT+/Io1sQ4HfELzYUrMBH26byDTJpJAOhhtUpBEa8zOiKejFVxEP7FyfnlsofQ3+yjZryt9vwm4GMo6mp0Md8eEJ6sPIxnq9OQGGyC9Q9GI+1RqeNPV4a6AnuwtnE8foN4qpAtiWIvrE0MJXL2XOwg/CMKyL6eNy4SlR8harkmF4mRjACBNiLVuAlDOIa1cYhX6m4ZCnRhxCNMg4Hu+45oAaDiMnDyCO3u0QUZm97A1h30p8h2SAHyy+mUbGdJN4b8V/taU6BgsC/9J2ZeA26ac8TQ08yBPDvQXgbfIhOTEvUM3bj54+f4CiuqSeY9M1/2VHnCkuuLzpOYFTs2QhjXx4muMgs3BvJ92+7fpp/0JXFxrt82FMEndLB1Koq+e7IuUofiu5SXREMQhUKDTgdCj9NYa1fto9ho0dGMkeJC2XeB70aA3FXg+ibSijcIqepMOiuQVckrt8Y+bKwTYymEbg7LZISWOrgWVmQ04S6BDWLiHpaziFlcymUXm+uRadThTiHaRjLz2g7Zta4bnR4sv4EgRwfhN6bTyT2KNQKrcTyEzL+G4=
  - secure: Pkcx4Bi5i3oaawT2T4MjBP6AXa1bD2r7fskoM5VupAuPyfsBpXz18UDUIXRxSjUHj6KkWcMp9f8jTXmYE2rhOr4izMwvUBFv6YFrk2TYvrn8vXnYdkEJ76VtrwNGzVo6WnNqLKZaorrf5MIR0qoRxVyYiFRaNIBi9EJNOvQ7bYvrLRh8L4Xd8nI5z10noOfloCmNtmQStOUShkKzwdY5qBXuNjD7kOTlk9u8DIzHHN7rZG2ESnUC0Ni9PnWSZcq87Ko5YBl/6qLnvjp1W+jtsAqGyT4E2Wv2yvjF1wvQsMLvpgQm1/2i+dtgd17QwUE6IKBuwlHhRexR4mFXRomZoNqG9JCwO+N4XVXa1PBl3NSodL0EVchcy/XHw1msNhbptu2Y/Taz9jULoh6tpEl3hgYlnYCDxJNMn5fO7zHS9Ybzv8gSdUwOePV2wy8MqcYPNfK8x1FFXJPgT9q5rKFHmdWiu4T+LFESBEnHl84DJyYgqpR6EeA6IBTi2ag663urKJLh3rpYaSfQ4WngrNfDKuiVlU9Ym6f45T+3CVFgE2L07JMjeZQX0BDtQ/GeC3+JG69K5NeLpqRTpafuCJzYddhUW51wJ9jD4pyiWSNSSuqMvvlNtHRKpQdSflmXNvFd79NKXPKm/Xslw7Q2eeiZwD2GdFj/tuecrGUoGsVStog=
